### ISSUE TITLE
How do i even install it?

### ISSUE THREAD

**Issue by s4mim** [MisterSandman7/Fetch#3]
Hi, im a beginner with using python. how do install this?

**Comment by MisterSandman7** [comment]
You'll need a couple of things:

1. Clone the repository
2. Add a **debug** folder to the project folder (needed for output.log)
3. create a **tokens.py** file in the project folder, this file will have to contain the following variables:

- discord_token
- consumer_token
- consumer_secret
All these will have to be strings, the first one is your bot token (from Discord development portal) and the other two are from the Twitter API application.

If not installed, remember to install discord.py and tweepy. I also suggest to have a database (SQLite3) application to open, read and modify the database if needed.

**Comment by s4mim** [comment]
Do you have a template for the tokens.py? mine is constantly giving ImportError.

**Comment by MisterSandman7** [comment]
![Screenshot_20210207_171333](https://user-images.githubusercontent.com/39649895/107152389-d7eb4480-6967-11eb-8542-f62967509853.png)
